global:
  scrape_interval: 15s  # Prometheus va scrapper toutes les 15 secondes
  evaluation_interval: 15s

scrape_configs:
  - job_name: "air_quality_api"
    metrics_path: "/metrics"      # endpoint exposant les metrics Prometheus
    static_configs:
      - targets:
          - "35.180.29.20:8000"   # l'IP publique de ton API et le port expos√©
